name: Git Action Pipeline

on:
  push:
    branches: main
    
# env:
#   EC2_KEY: ${{ secrets.GAMING_UNIX_SERVER_PRIVATE }}
    

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
        
      - name: Install Dependencies
        run: npm install
        
      - name: Build React App
        run: npm run build
        
  package:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AppPackage
          path: build/
          
  deployment:
    needs: package
    runs-on: ubuntu-latest
    
    steps:
          
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 44.205.244.220
          username: ubuntu
          key: ${{ secrets.GAMING_UNIX_SERVER_PRIVATE }}
          source: build/
          target: /home/ubuntu/react/target_location/
    
          
#       - name: Connect to EC2 server and perform deployment steps
#         run: |
#           echo "${{ secrets.GAMING_UNIX_SERVER_PRIVATE }}" > private_key.pem && chmod 600 private_key.pem
#            ssh -o "StrictHostKeyChecking=no" -i "private_key.pem" ubuntu@ec2-35-175-150-253.compute-1.amazonaws.com '
#             # Clean the drop folder
#             rm -rf /home/ubuntu/react/drop_location/*
            
#             # Clean the unzip folder
#             rm -rf /home/ubuntu/react/unzip_location/*

#             # Download the deployable zip package
#             scp /AppPackage.zip ubuntu@35.175.150.253:/home/ubuntu/react/drop_location/

#             # Unzip the deployable package
#             unzip /home/ubuntu/react/drop_location/AppPackage.zip -d /home/ubuntu/react/unzip_location/
            
#             # Clean the target folder
#             rm -rf /home/ubuntu/react/target_location/*

#             # Copy the unzipped content to the target folder
#             scp -r --exclude="*.zip" /home/ubuntu/react/unzip_location/* /home/ubuntu/react/target_location/
#           '
