name: Git Action Pipeline

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
        
      - name: Install Dependencies
        run: npm install
        
      - name: Build React App
        run: npm run build
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AppPackage
          path: build/
    
          
      - name: Connect to EC2 server and perform deployment steps
        run: |
          echo "${{ secrets.GAMING_UNIX_SERVER_PRIVATE }}" > private_key.pem && chmod 600 private_key.pem
           ssh -o "StrictHostKeyChecking=no" -i "private_key.pem" ubuntu@ec2-35-175-150-253.compute-1.amazonaws.com '
            # Clean the drop folder
            rm -rf /home/ubuntu/react/drop_location/*
            
            # Clean the unzip folder
            rm -rf /home/ubuntu/react/unzip_location/*

            # Download the deployable zip package
            scp /AppPackage.zip ubuntu@35.175.150.253:/home/ubuntu/react/drop_location/

            # Unzip the deployable package
            unzip /home/ubuntu/react/drop_location/AppPackage.zip -d /home/ubuntu/react/unzip_location/
            
            # Clean the target folder
            rm -rf /home/ubuntu/react/target_location/*

            # Copy the unzipped content to the target folder
            scp -r --exclude="*.zip" /home/ubuntu/react/unzip_location/* /home/ubuntu/react/target_location/
          '
